/********************************************************************************
 Module	        : Port
 File Name	: Port_PBcfg.c
 Author		: Yasser Waleed
 Description    : Source file containing the post-build configurations
*********************************************************************************/
/********************************************************************************
 INCLUDES
*********************************************************************************/
#include "Port.h"
/********************************************************************************
 VERSIONS CHECK
*********************************************************************************/
/* Module Version 1.0.0 */
#define PORT_PBCFG_SW_MAJOR_VERSION             (1U)
#define PORT_PBCFG_SW_MINOR_VERSION             (0U)
#define PORT_PBCFG_SW_PATCH_VERSION             (0U)

/* AUTOSAR Version 4.0.3 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif
/********************************************************************************
 INITIALIZATION FOR ALL PORT PINS
*********************************************************************************/
const Port_ConfigType PortConfigrations = {
	/*PORT NUM  , PIN NUM    , DIRECTION   , I.RES  , LVL , PIN MODE	  , DIR CHANGEABILITY  , MODE CHANGEABILITY*/  
	PORT_PORT_A , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_1 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_4 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_5 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_6 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_A , PORT_PIN_7 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
																																												   
	PORT_PORT_B , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_1 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_4 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_5 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_6 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_B , PORT_PIN_7 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
																																												   
	PORT_PORT_C , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_1 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_4 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_5 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_6 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_C , PORT_PIN_7 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
																																												   
	PORT_PORT_D , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_1 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_4 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_5 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_6 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_D , PORT_PIN_7 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
																																												   
	PORT_PORT_E , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_E , PORT_PIN_1 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_E , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_E , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_E , PORT_PIN_4 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_E , PORT_PIN_5 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
																																												   
	PORT_PORT_F , PORT_PIN_0 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_F , PORT_PIN_1 , PORT_PIN_OUT, OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_F , PORT_PIN_2 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_F , PORT_PIN_3 , PORT_PIN_IN , OFF    , LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE,
	PORT_PORT_F , PORT_PIN_4 , PORT_PIN_IN , PULL_UP, LOW , PORT_PIN_MODE_DIO , DIR_IS_CHANGEABLE  , MODE_IS_CHANGEABLE
};
/*******************************************************************************
 END OF FILE                                     
********************************************************************************/
